### ISSUE TITLE
[Bug] ROS 2 map topic not publishing

### ISSUE THREAD

**Issue by hwoithe** [eclipse-zenoh/zenoh-plugin-dds#135]
### Describe the bug

Using two Zenoh bridges, a ROS 2 map published in domain one does not publish for subscribers in domain zero.

### To reproduce

In ROS 2 Humble we can publish a map (OccupancyGrid) and subscribe to it with the following commands. (I am using `export ROS_LOCALHOST_ONLY=1` throughout.)

```
ros2 run nav2_map_server map_server --ros-args -p yaml_filename:=/opt/ros/humble/share/turtlebot3_navigation2/map/map.yaml
ros2 run nav2_util lifecycle_bringup map_server
ros2 topic echo /map
ros2 run rviz2 rviz2
```

In RViz, add the `/map` topic and change the topic's durability policy to transient local and a map will appear.

Close everything and start again from scratch. Clone zenoh-plugin-dds into your workspace, I am currently using commit 62006dfa, and build it. Start two bridges.

```
ros2 run zenoh_bridge_dds zenoh_bridge_dds -f --no-multicast-scouting -d 0 -l tcp/localhost:7447
ros2 run zenoh_bridge_dds zenoh_bridge_dds -f --no-multicast-scouting -d 1 -e tcp/localhost:7447
```

Then, start the other nodes.

```
ROS_DOMAIN_ID=1 ros2 run nav2_map_server map_server --ros-args -p yaml_filename:=/opt/ros/humble/share/turtlebot3_navigation2/map/map.yaml
ROS_DOMAIN_ID=1 ros2 run nav2_util lifecycle_bringup map_server
ros2 topic echo /map
ros2 run rviz2 rviz2
```

The echo will hang and RViz will not show the `/map` topic, although `ros2 topic list` will list it. Close everything and start again from scratch.

```
ROS_DOMAIN_ID=1 ros2 run nav2_map_server map_server --ros-args -p yaml_filename:=/opt/ros/humble/share/turtlebot3_navigation2/map/map.yaml
ROS_DOMAIN_ID=1 ros2 run nav2_util lifecycle_bringup map_server
ros2 run zenoh_bridge_dds zenoh_bridge_dds -f --no-multicast-scouting -d 0 -l tcp/localhost:7447
ros2 run zenoh_bridge_dds zenoh_bridge_dds -f --no-multicast-scouting -d 1 -e tcp/localhost:7447
ros2 topic echo /map
ros2 run rviz2 rviz2
```
Both echo and RViz will now work. In RViz, it will even show the map without changing the durability to transient local.

I expect the execution order not to matter.

### System info

Platform: Ubuntu 22.04.2 LTS
CPU: Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz
Zenoh environment: zenoh-plugin-dds (62006dfaacb1bb96c5c2ecafe07c588e9ec8641c)

**Comment by JEnoch** [comment]
We recently developed a new bridge for ROS 2: https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds
I recommand you switch to this one as it better integrates with ROS 2 and brings these benefits:

- Better integration of the ROS graph (all ROS topics/services/actions can be seen across bridges)
- Better support of ROS toolings (ros2 CLI, rviz2...)
- Configuration of a ROS namespace on the bridge (instead of on each ROS Node)
- Services and Action as Zenoh Queryables with more efficiency and scalability that RPC over DDS
- Even more compact discovery information between the bridges (not forwarding all ros_discovery_info messages as such)

RViz and the `ros2` commands are working smoothly with it, as I showed in a demo at ROSCon 2023.

The Zenoh plugin for DDS will eventually be deprecated for ROS 2 usage.
