### ISSUE TITLE
Windows plugin distribution is empty

### ISSUE THREAD

**Issue by samcarey** [eclipse-zenoh/zenoh-plugin-dds#156]
### Describe the bug

See bottom of screenshot below. The size is 22 bytes and is a zipped empty folder.
![image](https://github.com/eclipse-zenoh/zenoh-plugin-dds/assets/6446240/e3d50d2e-06a6-47ca-a682-b781e7c355cc)

### To reproduce

Go to https://download.eclipse.org/zenoh/zenoh-plugin-dds/latest/x86_64-pc-windows-msvc/ , download the plugin, and then unzip it.

### System info

NA

**Comment by JEnoch** [comment]
The fix was pushed in master and resulting package for Windows is now available in each [Release action](https://github.com/eclipse-zenoh/zenoh-plugin-dds/actions/workflows/release.yml). For instance, see the Artifacts at the bottom of the latest run: https://github.com/eclipse-zenoh/zenoh-plugin-dds/actions/runs/6773157566
