### ISSUE TITLE
Combine Zenoh-plugin-dds with Cyclone iceoryx shared memory

### ISSUE THREAD

**Issue by eliasdc** [eclipse-zenoh/zenoh-plugin-dds#50]
The `Zenoh-plugin-dds` fails to start when an unknown configuration is found in the configuration of Cyclone (`CYCLONEDDS_URI`). After enabling shared memory zenoh reports an error on start: 
```
1634811842.307391 [] async-std/: config: //CycloneDDS/Domain: SharedMemory: unknown element (file:///home/elias/tractonomy/shm_test_ws/src/ros2_shm_demo/cyclonedds.xml line 22)
```

The goal is to increase performance on the local machine through iceoryx while still maintain the possibility to connect remotely over WiFi using Zenoh. I'm using ROS2 Galactic, Cyclone DDS with iceoryx support and zenoh_plugin_dds ros2 node from this repository (`master` branch).

## cyclonedds.xml
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/iceoryx/etc/cyclonedds.xsd">
    <Domain id="any">
         <General>
            <NetworkInterfaceAddress>lo</NetworkInterfaceAddress>
            <AllowMulticast>default</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>64000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
            <MinimumSocketReceiveBufferSize>10MB</MinimumSocketReceiveBufferSize>
            <AssumeMulticastCapable>lo</AssumeMulticastCapable>
        </Internal>
        <SharedMemory>
            <Enable>true</Enable>
            <SubQueueCapacity>256</SubQueueCapacity>
            <SubHistoryRequest>16</SubHistoryRequest>
            <PubHistoryCapacity>16</PubHistoryCapacity>
            <LogLevel>info</LogLevel>
        </SharedMemory>
    </Domain>
</CycloneDDS>
```

## how to reproduce
Using the [ros2_shm_demo](https://github.com/ApexAI/ros2_shm_demo) sample code it is easy to reproduce with the following steps. 
- create new workspace
- clone `zenoh-plugin-dds` in `src` folder
- clone `ros2_shm_demo` in `src` folder
- `rosdep install --from-paths . --ignore-src -r -y`
- `colcon build`
- edit `src/ros2_shm_demo/cyclonedds.xml` to correspond my config given at the top of this issue.
- `export CYCLONEDDS_URI=file://$PWD/src/ros2_shm_demo/cyclonedds.xml`
- `. install/setup.bash`

Do not forget to export `CYCLONEDDS_URI` and source your workspace in each terminal before every command.

### Terminal 1
```bash
ros2 run ros2_shm_demo listener
```

### Terminal 2
```bash
ros2 run ros2_shm_demo talker
```

### Terminal 3
``` bash
iox-roudi
```
You should see the talker and listener communicate using Shared Memory (iceoryx).

### Terminal 4
``` bash
RUST_LOG=info ros2 run zenoh_bridge_dds zenoh_bridge_dds
```
#### Expected result
I would assume it would ignore the Shared Memory configuration and try to discover nodes using the local loopback interface. However it fails on recognizing the `<SharedMemory>` tag from the config file and hangs without discovering any nodes, topics, etc.

Starting an additional echo on the topic does work when adding the ROS msg type:
``` bash
ros2 topic echo /chatter ros2_shm_demo/msg/ShmTopic
```

**Comment by eliasdc** [comment]
By replacing the command in terminal 4 with the following: 
```
CYCLONEDDS_URI=$ZENOH_CYCLONEDDS_URI RUST_LOG=info ros2 run zenoh_bridge_dds zenoh_bridge_dds
```
Where `ZENOH_CYCLONEDDS_URI` is the same file as the one used by ros2 with the exception of the `<SharedMemory>` tag.

I still need to test if sub and pub works on multiple hosts. Isn't an easy fix just to ignore unknown tags from the xml config file?

**Comment by JEnoch** [comment]
> By replacing the command in terminal 4 with the following:
> `CYCLONEDDS_URI=$ZENOH_CYCLONEDDS_URI RUST_LOG=info ros2 run zenoh_bridge_dds zenoh_bridge_dds`
> Where `ZENOH_CYCLONEDDS_URI` is the same file as the one used by ros2 with the exception of the `<SharedMemory>` tag.

So, did it work ?

> I still need to test if sub and pub works on multiple hosts.

You can test this with a similar deployment than described here:
https://github.com/eclipse-zenoh/zenoh-plugin-dds#2-hosts-avoiding-udp-multicast-communication

> Isn't an easy fix just to ignore unknown tags from the xml config file?

CycloneDDS v0.7.0 is reading this file, not zenoh_bridge_dds. Thus such fix would have to go in a CycloneDDS v0.7.x version, and zenoh_bridge_dds would need to use this new version.

**Comment by eliasdc** [comment]
It does not work. I tested by subscribing to a topic with a fixed size message and I'm not receiving those messages. Only when I make sure the topic is not using shared memory (by using dynamic size message, e.g. String) I receive the messages.

**Comment by JEnoch** [comment]
Hi @eliasdc,

I tried to reproduce your issue on a fresh Ubuntu 20.04 with ROS2 Galactic built from sources. I followed your steps, but to simulate another host, I ran a 2nd bridge and the `ros2 topic echo` command in DDS domain 1.

## Terminal 1
```bash
export CYCLONEDDS_URI=file://$PWD/src/ros2_shm_demo/cyclonedds.xml
ros2 run ros2_shm_demo listener
```

## Terminal 2
```bash
export CYCLONEDDS_URI=file://$PWD/src/ros2_shm_demo/cyclonedds.xml
ros2 run ros2_shm_demo talker
```

## Terminal 3
```bash
iox-roudi
```
At this stage the talker and the listener are communicating via Iceoryx

## Terminal 4
```bash
export CYCLONEDDS_URI=$ZENOH_CYCLONEDDS_URI
RUST_LOG=zp=debug ros2 run zenoh_bridge_dds zenoh_bridge_dds --rest-plugin
```
Where:
 - `$ZENOH_CYCLONEDDS_URI` points to the same file as the one used by ros2 with the exception of the `<SharedMemory>` tag
 - `RUST_LOG=zp=debug` activates the debug logs but only for the zenoh-plugin-dds code
 - `--rest-plugin` activates the zenoh REST API on http://localhost:8000 

At this stage, I can see in the logs that the bridge discovered the DDS readers and writers on topic `rt/chatter` (corresponding to ROS2 topic `/chatter`). This is confirmed looking in the zenoh [admin space](https://github.com/eclipse-zenoh/zenoh-plugin-dds#admin-space) on http://localhost/@/**/chatter : both readers and writers have been discovered and 2 routes (from_dds + to_dds) have been created for this topic.
Note that this discovery occurred via DDS over UDP multicast (since the bridge doesn't support Iceoryx).

## Terminal 5
```bash
export CYCLONEDDS_URI=$ZENOH_CYCLONEDDS_URI
Z_LOG_PAYLOAD=true RUST_LOG=zp=trace ros2 run zenoh_bridge_dds zenoh_bridge_dds -d 1
```
Where:
 - `RUST_LOG=zp=trace` activates the trace logs but only for the zenoh-plugin-dds code
 - `Z_LOG_PAYLOAD=true` makes the bridge to also log the payload of routed messages (useful to debug what's routed)
 - `-d 1` configure the bridge to use the DDS Domain 1

When starting, the bridge is detected by the bridge running in terminal 4, as confirmed by such log:
`[2021-11-17T17:00:32Z DEBUG zplugin_dds] New zenoh_dds_plugin detected: ...`

## Terminal 6
```bash
export CYCLONEDDS_URI=$ZENOH_CYCLONEDDS_URI
ROS_DOMAIN_ID=1 ros2 topic echo /chatter ros2_shm_demo/msg/ShmTopic
```
Now, I can see in terminal 5 that the bridge on DDS Domain 1 correctly discovered the DDS entities declared by this `ros2 topic` command, and that is starts routing messages on topic `rt/chatter`.
And in terminal 6, I see the `ros2 topic` command receiving the talker's publications.

If I kill the bridge in terminal 5 (or in terminal 6), the `ros2 topic` command stops receving publications. 

----

So it works as I expected for me.
Could you please try the exact steps described above, and let me know if you see a different behaviour ?
Or if you have a different use case that's failing, please detail it.

**Comment by eliasdc** [comment]
Hi,

I tested both now (local and multiple machines) and everything is working. My mistake was that the shared memory cyclonedds config file was using a `tag` which isn't supported yet in the cyclone version used by Zenoh, which caused the subscriber to ignore the topic.

So the workaround does work. I was even using the localhost interface on the multi host setup. 

Thanks for the help!
